project:
  type: website
  output-dir: docs
  
website:
  title: "BIOL B215: Biostatistics with R"
  site-url: https://bbitarello.github.io/b215f2026/
  repo-url: https://github.com/bbitarello/b215f2026
  repo-branch: main
  repo-actions: [source]
  search: 
    location: sidebar
  sidebar:
    background: primary
   # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bbitarello/b215f2026
        text: GitHub
      - icon: cloud-fill
        href: https://posit.cloud/spaces/678147/join?access_code=hl0WMhTu8LNwvW1hn-uIdm_lx1Xm8sCjIUMwCW24
        text: RStudio Cloud
    style: "docked"
    contents:
    - href: index.qmd
      text: Home
   # - href: syllabus.qmd
  #    text: Syllabus
  #  - href: schedule.qmd
  #    text: Schedule
  #  - href: slides.qmd
  #  - href: CA1.qmd
  #    text: Coding Assignment 1
    - href: rlearn.qmd
      text: R resources
  
    
format:
  html:
    theme: 
     - journal
     - styles.scss
    toc: true
   


editor: source