project:
  type: website
  output-dir: docs
  # Comment first lines to make faster previews
website:
  title: "BIOL B215: Biostatistics with R"
  site-url: https://bbitarello.github.io/b215f2026/
  repo-url: https://github/bbitarello/b215f2026/
  repo-branch: main
  repo-actions: [source]
  sidebar:
    background: primary
   # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bbitarello/b215f2026
        text: GitHub
      - icon: cloud-fill
        href: https://posit.cloud/spaces/807519/content/all?sort=name_asc
        text: Posit Cloud
    style: "docked"
    contents:
   # search: true
    - href: index.qmd
      text: Schedule
    - href: syllabus.qmd
      text: Syllabus
    - href: rlearn.qmd
      text: Rrresources
    - href: slides.qmd
      text: Slides
  #  - href: CA1.qmd
  #    text: Coding Assignment 1
   # - href: labs.qmd
   #   text: Labs
   # - href: rlearn.qmd
  #    text: Learning resources
format:
  html:
    theme: 
     - cosmo
     - styles.scss
    #axe:
    #  output: 
    fig-cap-location: margin
    #toc: true
    self-contained: true
   
editor: source