---
title: "B215: Biostatistics with R"
subtitle: "Schedule (subject to change)"
date: 2026-08-30
date-format: long
date-modified: last-modified
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses and the timeline of topics and assignments might be updated throughout the semester.

```{r, echo = FALSE, message = FALSE, warning = FALSE}
suppressPackageStartupMessages(library(googlesheets4))
suppressPackageStartupMessages(library(gt))
suppressPackageStartupMessages(library(tidyverse))
gs4_deauth()
```

::: column-screen-right
```{r, echo = FALSE, eval=F, message=FALSE}
#this code chunk was borrowed from: https://github.com/sta199-summer-1/sta199-summer-1.github.io/tree/main
d <- read_sheet("https://docs.google.com/spreadsheets/d/1ScIXAwu759O7g2WS4HWBmvgP50oKnPCLGW0qb33H67Y/edit?usp=sharing", sheet = "Schedule-new")
g<-d |>
  mutate(
    #Date = as.Date(date),
    week = ifelse(is.na(week), "", week),
    module = ifelse(is.na(module), "", module),
    dow = ifelse(is.na(dow), "", dow),
    prep = ifelse(is.na(prep), "", prep),
    `in-class` = ifelse(is.na(`in-class`), "", `in-class`)
    
  ) |>
  gt()
#g |>
#  text_transform(cells_body(columns = c(module, week, dow, date)),
#                 fn = function(x) {
#      ifelse(is.na(x), paste0(""), x)}) |>
#  text_transform(cells_body(columns = c(prep)),
#    fn = function(x) {
#      ifelse(is.na(x), fontawesome::fa("book", fill_opacity = 0.1),
#        glue::glue("<a href = {x}>{fontawesome::fa('book')}</a>")
#      )
#    }
#  ) |>
g1<-g |>  text_transform(cells_body(columns = c(class_slides)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("laptop", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>")
      )
    }
  ) |>
    text_transform(cells_body(columns = c(lab_slides)),
    fn = function(x) {
      ifelse(is.na(x), fontawesome::fa("laptop", fill_opacity = 0.1),
        glue::glue("<a href = {x}>{fontawesome::fa('laptop')}</a>")
      )
    }
  ) |>
 text_transform(cells_body(columns = c(exam)),
    fn = function(x) {
      ifelse(is.na(x), "",glue::glue("<a fontawesome::fa('file-circle-check')</a> {x}"))
      })|>
  fmt_date(date, date_style = 9) |>
  sub_missing(columns = c(date, what, topic, due), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(module,week, dow,  class_slides, lab_slides)
    ) |>
  cols_align(
    align = "left", 
    columns = c(date, what, topic, prep, exam, due)
    ) 
g1
```


```{r, echo = FALSE, warning=F, message=F, fig.width=100}
#this code chunk was borrowed from: https://github.com/sta199-summer-1/sta199-summer-1.github.io/tree/main
d <- read_sheet("https://docs.google.com/spreadsheets/d/1ScIXAwu759O7g2WS4HWBmvgP50oKnPCLGW0qb33H67Y/edit?usp=sharing", sheet = "Schedule-new")
g<-d |>
  mutate(
    #Date = as.Date(date),
    week = ifelse(is.na(week), "", week),
    module = ifelse(is.na(module), "", module),
    dow = ifelse(is.na(dow), "", dow),
    due = ifelse(is.na(due), "", due)
  ) |> select(
    module, week, dow, date, what, topic, due,exam) |>
  gt()

g1<-g|> text_transform(cells_body(columns = c(exam)),
    fn = function(x) {
      ifelse(is.na(x), "",glue::glue("<a fontawesome::fa('file-circle-check')</a> {x}"))
      })|>
  fmt_date(date, date_style = 9) |>
  sub_missing(columns = c(date, what, topic), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(module,week, dow)
    ) |>
  cols_align(
    align = "left", 
    columns = c(date, what, topic, exam, due)
    ) 
g1 |> cols_width(week ~ px(50), module ~ px(50), dow ~ px(40), date ~ px(80), what ~ px(50), topic ~ px(150), due~ px(100),exam ~ px(100))
```
:::
