---
title: "Learning R (and statistics)"
number-sections: false
toc: true
---

Updated often. If you're an enrolled students and would like to contribute content here, please open a thread on Piazza under "Misc" and say you'd like to share a useful link.

## Getting help with R {#r-help}

**START HERE**, with [fbriatte.org](https://f.briatte.org/r/asking-r-questions), where you can learn how to find answers to your burning R questions online.

-   [Getting help with R](https://www.r-project.org/help.html)
-   Stack overflow: topics are tagged, and “r” is a very popular tag on the site. To go directly to R-related topics, visit [http://stackoverflow.com/questions/tagged/r](%5Bhttp://stackoverflow.com/questions/tagged/r).
-   [Rstudio Community](https://community.rstudio.com/)
-   Reddit: r/rstats, r/Rlanguage, r/rprogramming, r/RStudio
-   Github: github is a must for anyone in datascience and has many functions. For your purposes, searching for a particular package and looking into their "issues" page can be very helpful. E.g., [here](https://github.com/rstudio/rmarkdown/issues) is the issues page for the `rmarkdown` package.

- [Cheatsheets (several)](https://opensource.posit.co/resources/cheatsheets/)

## Free Online Books

- ["Applied Data Skills"](https://psyteachr.github.io/ads-v2/)
- ["Exploring Data Science with R and the Tidyverse: A Concise Introduction"](https://ds4world.cs.miami.edu/)

- ["R Graphic Cookbook"](https://r-graphics.org/)

-   ["R Markdown Cookbook"](https://bookdown.org/yihui/rmarkdown-cookbook/)

-   ["Introduction to Data Science: Data Wrangling and Visualization with R"](https://rafalab.dfci.harvard.edu/dsbook-part-1/R/intro-to-R.html), by Rafael Irizarry

-   ["Introduction to Data Science: Statistics and Prediction Algorithms Through Case Studies"](https://rafalab.dfci.harvard.edu/dsbook-part-2/), by Refael Irizarry

-   ["R for Data Science"](https://r4ds.had.co.nz/), by Hadley Wickham & Garrett Grolemund

-   ["YaRrr! The Pirate’s Guide to R"](https://bookdown.org/ndphillips/YaRrr/), by Nathaniel Phillips

-   ["An introduction to Biostatistics using R"](https://waveland.com/Glover-Mitchell/r-guide.pdf), by Glover & Mitchell

-   ["Introductory Biostatistics with R"](https://tuos-bio-data-skills.github.io/intro-stats-book/), by Dylan Childs, Bethan Hindle & Philip Warren

-   ["Applied Biostats"](https://ybrandvain.github.io/biostats/), by Yaniv Brandvain.

-   ["ggplot2: Elegant Graphics for Data Analysis (3e)"](https://ggplot2-book.org/)




## Videos {#r-vids}


- [Overview of R Markdown: a crash course](https://youtu.be/mcTB7h9lpCg?si=oLCBDUIGKL2Dowdn)
-   [Code Like a Pro](https://www.youtube.com/watch?embed=no&v=91LmBj29-Sc&list=PLA3ArwPxU4My_bKb7bJrb78aq5Gx1rTfs&index=7)
-   [Intro to Rstudio and Rstudio Cloud](https://www.youtube.com/watch?embed=no&v=mcTB7h9lpCg&list=PLA3ArwPxU4My_bKb7bJrb78aq5Gx1rTfs&index=8&ab_channel=JoshuaFrench)
-   [Overview of R markdown](https://www.youtube.com/watch?embed=no&v=mcTB7h9lpCg&list=PLA3ArwPxU4My_bKb7bJrb78aq5Gx1rTfs&index=8&ab_channel=JoshuaFrench)
-   [Rmarkdown with Rstudio](https://www.youtube.com/watch?embed=no&v=DNS7i2m4sB0&list=PLA3ArwPxU4My_bKb7bJrb78aq5Gx1rTfs&index=9&t=2s&ab_channel=RogerPeng)
-   [This youtube playlist](https://www.youtube.com/playlist?embed=no&list=PLA3ArwPxU4MxphgeREPfnxznb8llUtTzX) - I curated this and it contains both R info and biostatistics in general.

## Tutorials & Simulations


- [r-statistics.co, by Selva Prabhakaran](https://r-statistics.co/) - includes [very good section on ggplot](https://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html)!

-   [From your textbook](https://whitlockschluter3e.zoology.ubc.ca/)
-   [Quick-R](https://www.statmethods.net/r-tutorial/index.html)
-   [Rstudio Education](https://education.rstudio.com/learn/beginner/)
-   [Posit Cloud Recipes](https://posit.cloud/learn/recipes)
- [Power analyses in R](https://data-wise.github.io/doe/appendix/r-packages/pwr.html)

## Web visualizations

CLT: [https://www.zoology.ubc.ca/~whitlock/Kingfisher/CLT.htm](https://www.zoology.ubc.ca/~whitlock/Kingfisher/CLT.htm)



CLT: [https://shiny.maths.nottingham.ac.uk/pmzdjc/YujingCLTApp/?showcase=0](https://shiny.maths.nottingham.ac.uk/pmzdjc/YujingCLTApp/?showcase=0)


Another one from CLT: [https://shiny.maths.nottingham.ac.uk/pmzdjc/YujingCLTApp/?showcase=0](https://shiny.maths.nottingham.ac.uk/pmzdjc/YujingCLTApp/?showcase=0)

Sampling from the Normal:
[https://brandvain.shinyapps.io/standardnormal/](https://brandvain.shinyapps.io/standardnormal/)

Sample means with a normal distribution:
[https://www.zoology.ubc.ca/~whitlock/Kingfisher/SamplingNormal.htm](https://www.zoology.ubc.ca/~whitlock/Kingfisher/SamplingNormal.htm)


Confidence intervals for the mean:
[https://www.zoology.ubc.ca/~whitlock/Kingfisher/CIMean.htm](https://www.zoology.ubc.ca/~whitlock/Kingfisher/CIMean.htm)


This link has web apps for several topics covered in the course: [https://shinyapps.science.psu.edu/](https://shinyapps.science.psu.edu/)


## Freely Available (Biological) Datasets

I will keep adding stuff here, but here are some good places to search.

* [Dryad](https://datadryad.org/) - lots of scientific papers make their datasets available here.
* [Zenodo](https://zenodo.org/) - lots of scientific papers make their datasets available here.
* [National Library of Medicine Dataset Catalog](https://datasetcatalog.nlm.nih.gov/) - great resource from the NIH, points to datasets elsewher elike zenodo, dryad, figshare,  etc.
* [re3data](https://www.re3data.org/)
* [FigShare]() - lots of scientific papers make their datasets available here.
* [Wold Population Review](https://worldpopulationreview.com/) - not focused on biology but very cool nevertheless. There are subsections that have biological datasets though like the one focusing on health, for example. 


# Articles \& Other Resources


* Statistics for Biologists - *Nature* collection of articles highlighting important statistical issues that biologists should be aware of and provides practical advice to help them improve the rigor of their work.[nature.com/collections/qghhqm](https://www.nature.com/collections/qghhqm)

* [G\*power](www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower): a tool to compute statistical power analyses for many different t tests, F tests, χ2 tests, z tests and some exact tests. G*Power can also be used to compute effect sizes and to display graphically the results of power analyses.
[www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower](https://www.psychologie.hhu.de/arbeitsgruppen/allgemeine-psychologie-und-arbeitspsychologie/gpower)

* The `pwr` package in R is a powerful tool for conducting power analysis. Power analysis is essential in determining the sample size needed to detect an effect of a given size with a certain level of confidence. It is widely used in experimental design and statistical hypothesis testing.
[data-wise.github.io/doe/appendix/r-packages/pwr.html](https://data-wise.github.io/doe/appendix/r-packages/pwr.html)

- [R markdown Gallery](https://rmarkdown.rstudio.com/gallery.html): Check out the range of outputs and formats you can create using R Markdown.