---
title: "Schedule"
number-sections: true
draft: true
---

## Lectures \& Labs {#sec-lec}

Please check often. Subject to change. New material is added approximately on a weekly basis.

Chapters refer to the assigned textbook (3rd edition). Corresponding chapters exist in the 2nd edition but may have a different number.

RL: recorded lecture (Moodle).

# Module 1: Intro to Statistics and R

| Week | Dates | Topic | Prep|
|:--|:---|:-------|:-------|
| 1 | 8/31 | 0.0 Logistics| Pre-course survey |
| 1 | 9/1 | Lab 1: Rstudio/R introduction    | DC[^2] *Introduction to R*|
| 1 | 9/2 |   | Ch. 1, RC 1.2
| 2 | 9/7 | Labor day (no classes)||
| 2 | 9/8 | Lab 2  | |
| 2 | 9/9 | 1.2  | |
| 3 | 9/14 | ||
| 3 | 9/15 | Lab 3  | |
| 3 | 9/16 |   | |
| 4 | 9/21 | ||
| 4 | 9/22 | Lab 4| |
| 4 | 9/23 | | |
| 5 | 9/28 | ||
| 5 | 9/29 | Lab 5  | |
| 5 | 9/30 | 1.2  | |


# Module 2: NAME THIS

| 6 | 10/5 | ||
| 6 | 10/6 | No lab (Midterm 1) | |
| 6 | 10/7 |   | |

| | 10/12-10/14 | No classes (Fall break!)||

| 7 | 10/19 | ||
| 7 | 10/20 | Lab 7  | |
| 7 | 10/21 |  | |

| 8 | 10/26 | ||
| 8 | 10/27 | Lab 8  | |
| 8 | 10/28 |  | |


| 9 | 11/2 | | |
| 9 | 11/3 | Lab 9 | |
| 9 | 11/4 |  | |

| 10 | 11/9 | | |
| 10 | 11/10 | Lab 9  | |
| 10 | 11/11 |  | |


| 11 | 11/16 | | |
| 11 | 11/17 | Lab   | |
| 11 | 11/18 | | |

| 12 | 11/23 | | |
| 12 | 11/24 | Lab   | |
| 12 | 11/25 | No in-person class (recorded lecture)| |

| 13 | 11/30 | | |
| 13 | 12/1 | Lab   | |
| 13 | 12/2 | | |


| 14 | 12/7 |  |  |
| 14 | 12/8 | Lab   |  |
| 14 | 12/9 | Review, Course Evaluations |  |


| Week | Dates | Topic | Recommended Readings |
|:--|:---|:-------|:-------|
| 1 | 8/31 | 1.1 Statistics & Samples| Ch. 1 |
| 1 | 9/1 | 1.2 Statistics & Samples | Ch.1, Interleaf 1: Correlation does not require causation |
| 1 | 9/2 | 1.3 Statistics & Samples| Ch.1, Interleaf 1: Correlation does not require causation |
|2 | 9/7| Labor day (no classes)| |
|2| 9/9|2.1 Displaying & Describing Data | Ch.2-3 |
| 3 | 9/17 | 2.2 Displaying & Describing Data (center)| Ch.2-3 |
| 4 | 9/22| 2.3 Displaying & Describing Data (spread)  | Ch.2-3 |
| 4 | 9/24 | 2.4 Displaying & Describing Data (plots) | Ch. 2-3 |
| 5 | 9/29 | 2.5 Displaying & Describing Data (plots) | Ch. 2-3 |
| 5 | 10/1 | 3.1 Probability | Ch.5 |
| 6 | 10/6 | 3.2 Probability | Ch.5 |
| 6 | 10/8 | 3.3 Probability | Ch.5 |
|  | 10/13 | No classes (Fall Break!) |  |
| 7 | 10/20 |3.4. Probability| Ch.4 |
| 7 | 10/22 | 4.1 Estimation  |  Ch.4|
| 8 | 10/27 | 4.2 Estimation| Ch.4|
| 8 | 10/30 | 4.3 Estimation| Ch.4 & Interleaf 2 |
| 9 | 11/3 | 4.4 Estimation| Ch.4 & Interleaf 2  |
| 9 | 11/5 | 5.1 Hypothesis Testing | Ch. 6 & Interleaf 3 |
| 10 | 11/10 | 5.2 Hypothesis Testing | Ch. 6 & Interleaf 3 |
| 10 | 11/12 | 5.3 Hypothesis Testing <br>  6.1 Proportions & Probability Models| Ch. 6 & Interleaf 3, Optional readings[^1] <br> Ch. 7| 
| 11 | 11/17 | 6.2 Proportions & Probability Models |  Ch. 7|
| 11 | 11/19 | 7.1. Goodness-of-fit tests  | Ch.8 |
| 12 | 11/24 | - Moved to 11/25: 7.2 Goodness-of-fit tests <br> 8.1 Contingency Analyses |  Ch.8 <br> Ch.9|
| 12 | 11/26 | No in-person class (recorded lecture posted on Moodle) | 8.2 Contingency Analyses |Ch.9  |
| 13 | 12/1 | 9.1 Normal Distribution | Ch.10 |
| 13 | 12/3 | 9.2 Normal Distribution  | Ch.10-11 |
| 14 | 12/8 | 9.3 Normal Distribution wrap-up <br> (If there's time, practice problems) | Ch.11.1-11.4 |
| 14 | 12/10 | Review Session, In-class time for Course Evals |  |

[^1]: Optional but recommended readings: (a) [Halsey et al. "The fickle P value generates irreproducible results". Nat Methods.](https://doi.org/10.1038/nmeth.3288), (b) [Nuzzo. "Scientific method: Statistical errors. Nature](https://doi.org/10.1038/506150a)

## Labs {#sec-labs}


| Week | Date  | Topic                     | Prep  |
|:-|:-|:-----|:--------------|
| 1    | 2/9   | Course Logistics          |       - |
| 1    | 2/9   | Rstudio/R introduction    | DC[^2] *Introduction to R*|
| 2    | 9/9   | Data Types                           | DC *Introduction to R* |
| 3    | 9/16  | Data Structures                           | DC *Introduction to Importing Data With R*     |
| 4    | 9/23  | Describing Data: Summary Statistics & Plots                           |  DC *Data Manipulation with dplyr* </br> *Introduction to the Tidyverse  (Grouping and Summarizing; Data Wrangling; Data Visualization; Types of visualizations)* |
| 5    | 9/30  |  R markdown, Tidyverse, & Exploratory Data Analysis                         | DC *Reporting with Rmarkdown (Getting Started; Adding Analyses and Visualizations)*    |
| 6    | 10/7  |Soft Intro to Loops and Sampling in R |DC *Introduction to Data Visualization with ggplot2*  </br>   DC *Data Manipulation with dplyr*
|      | 10/14 | NO LAB      |   (fall break!) |
| 7    | 10/21 |apply family and conditional statements|DC *Categorical Data in the Tidyverse*       </br>  DC   *Intermediate R (Loops)*    </br> Practice: DC *Conditionals and Control Flow*      |       |               |       |
| 8     | 10/28 | NO LAB  | (in class Midterm!)       |
| 9    | 11/4  | Writing Functions in R!                          |  DC *Intermediate R: Functions*      |
| 10    | 11/10 | Bootstrapping and Hypothesis Testing| DC *Sampling in R: Bootstrap  distributions* | 
| 11   | 11/18 |  Proportions and Binomials                        |       |
| 12   | 11/25 |   Lecture (make up for 11/24)                        |       |
| 13   | 12/2  | In class walk-through R examples seen in lectures (Goodness of fit, Contingency Analyses, Normal distr.)                          |       |
| 14   | 12/9  |In class time to work on CA2                  |       |


[^2]: DataCamp

## Problem sets {#sec-PS}

| Problem set | Topic | Due Date  | Difficulty  | Type      |
|:------------|:------|:----------|:------------|:----------|
| 1           |  Ch. 1-3     | Fri 10/3  | Easy/Medium | Formative |
| 2           |  Probability     | Wed 10/22 | Medium/Hard | Formative |
| 3           | Ch. 4 and Ch.6    | Thu 11/13  | Medium/Hard | Formative |
| 4-5[^6]           |  Ch.7-?    | W 12/11   | Medium/Hard | Formative |

[^6]: We decided based on polling to merge PS4-5 which will be worth 2x as many points as other PSs.

## Coding Assignments {#sec-LA}

| Coding Assignment | Topics | Due Date  | Difficulty | Type      |
|:------------------|:-------|:----------|:-----------|:----------|
| [Coding Assignment 1](CodingAssignments/CA1.html)                 | TBD    | Fri 11/7 | Hard       | Summative |
|Coding Assignment 2               | TBD    | Thu 12/11 | Hard       | Summative |

## Midterms {#sec-exams}

| Assessment | Topics     | When;Where                   | Difficulty | Type      |
|:------------|:------------|:---------------------|:------------|:------------|

| Midterm 1  | Module 1  | TBD; in-class        | Hard       | Summative |
| Midterm 2  | Module 2* | TBD; in-class | Hard       | Summative |
| Midterm 3  | Module 3 | Finals week; TBD | Hard       | Summative |

* statistics is cumulative, so though the focus for midterms 2 and 3 is on the respective modules listed, knowledge of prior modules is crucial.
## Office Hours {#sec-oh}

Please attend OH ***at least 3x*** during the semester (the more the merrier).


| Who | When[^3] | Where |
|:-----------------------|:-----------------------|:-----------------------|
| Professor drop-in hours | Monday 2-3pm | Park 211 |
| Professor drop-in hours | Wednesday 2-3pm | Park 211 |
| Professor drop-in hours | Thursday 4-5pm | Zoom[^4] |
| TA | TBD | TBD |

[^3]: Note: no drop-in hours on 9/8; 9/29; 10/13 and 10/15 (Fall break); 12/01

[^4]: Please email if planning to attend. If I am also available in person, I will send an announcement.

*If* you can't attend any of the times above you can schedule an appointment with me using my [calendly link.](https://moodle.brynmawr.edu/mod/page/view.php?id=403047&forceview=1)
